<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>mkpsf2fe</RootNamespace>
    <AssemblyName>mkpsf2fe</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\vgmtutil\vgmtutil.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="programs\mkpsf2.exe" CopyToOutputDirectory="Always" />
    <Content Include="programs\mkpsf2.txt" CopyToOutputDirectory="Always" />
    <Content Include="psf2s\dir.txt" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Form1.resx" />
    <EmbeddedResource Include="Properties\Resources.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="modules\cdvdnul.irx" />
    <None Include="modules\fakesif.irx" />
    <None Include="modules\myhost.irx" />
    <None Include="modules\psf2.irx" />
    <None Include="modules\sq.irx" />
    <None Include="Properties\Settings.settings" />
  </ItemGroup>
</Project>
